### ISSUE TITLE
docx2pdf-converter/convert.sh: No such file or directory

### ISSUE THREAD

**Issue by mourgias** [Bansnetsajak007/docx2pdf-converter#1]
When Im trying to execute the convert on Mac OS node js, I get the error docx2pdf-converter/convert.sh: No such file or directory.
I don't know if this is a bug, because I'm new in the world of the node js.

Thank you in advance.

**Comment by Bansnetsajak007** [comment]
Apologies for the confusion. I forgot to include the convert.sh file, but now it has been added. Please give it a try, and if you encounter any issues, feel free to let me know.
