### ISSUE TITLE
Does no work in Linux operating system 

### ISSUE THREAD

**Issue by mwashambw** [Bansnetsajak007/docx2pdf-converter#2]
I understand Converting docx to pdf is challenging. Thanks for this library but can you improve it to be able to work on linux operating system? I have deployed my webapp that do conversion of file from docx to pdf. But on render Hosting system it does not work. Error is throwncon logs, 'Powershel not found".

**Comment by hl0709** [comment]
I also found that it cannot be used on Linux systems. Do you have any solutions? Or there may be better alternatives

**Comment by mwashambw** [comment]
> I also found that it cannot be used on Linux systems. Do you have any solutions? Or there may be better alternatives

Still I have not found a solution for this

**Comment by Bansnetsajak007** [comment]
with this update  the docx-to-pdf npm package should now work on Linux systems as well. The package relies on the unoconv tool for conversion. To ensure proper functionality, please install unoconv by running sudo apt install unoconv. If you encounter any further issues or have additional questions, feel free to reach out.
